### ISSUE TITLE
does this work with node?

### ISSUE THREAD

**Issue by seguri** [sanity-io/jsonwebtoken-esm#2]
Hi,

Is this supposed to work with ECMAScript modules? Am I doing something wrong?

```
import { sign } from 'jsonwebtoken-esm'
var privateKey = fs.readFileSync('private.key')
var token = sign({ foo: 'bar' }, privateKey, { algorithm: 'RS256' })
```

throws

```
Error: Secure random number generation is not supported by this browser.
Use Chrome, Firefox or Internet Explorer 11
```

**Comment by stipsan** [comment]
Hi! You're not doing anything wrong, this project isn't intended to run on node. It's a last resort for poor souls that are migrating libraries to run in ESM native envs such as Vite, or otherwise runs entirely in the browser. It adds all sorts of heavy polyfills for node builtins and globals and I'd advice against trying to use this on node.

For ESM packages that are designed to work in both node's ESM mode, and browsers/bundlers, you'll see multi env exports like these: https://github.com/stipsan/get-random-values-esm/blob/07a580d47b52d71cd44d8cc7b5b67e44e8fac9be/package.json#L23-L29
